### Get Home Route
GET http://localhost:3000/api

### Add user to the DB
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Asrar Ahmed",
  "email": "asrar.doe@example.com",
  "password": "asrar123"
}

### Add user to the DB

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@example.com",
  "password": "securePassword123"
}

### User login

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "asrar.doe@example.com",
  "password": "asrar123"
}

### List out all the users

GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc3Jhci5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzc3OTY2MzgsImV4cCI6MTczNzgwMDIzOH0.BNmzQxbM_C934Gz3wMmOSVqTOR5N30niE509SnPlyOY

### Sort and search the user

GET http://localhost:3000/api/users?page=1&limit=5&search=As
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc3Jhci5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzc3OTY2MzgsImV4cCI6MTczNzgwMDIzOH0.BNmzQxbM_C934Gz3wMmOSVqTOR5N30niE509SnPlyOY

### Update User
PUT http://localhost:3000/api/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc3Jhci5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzc3OTY2MzgsImV4cCI6MTczNzgwMDIzOH0.BNmzQxbM_C934Gz3wMmOSVqTOR5N30niE509SnPlyOY
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com",
  "password": "newpassword12345"
}

### Delete User
DELETE http://localhost:3000/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc3Jhci5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3Mzc3OTY2MzgsImV4cCI6MTczNzgwMDIzOH0.BNmzQxbM_C934Gz3wMmOSVqTOR5N30niE509SnPlyOY

